version: "3.9"

services:
  api:
    build: .
    container_name: globant_de_api
    ports:
      - "8000:8000"
    volumes:
      # Persist the SQLite DB file outside the container
      - db_data:/app/globant.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  db_data:
